clear;
saveLocation = 'mp_result/lane7m-5vehicles-verticalZero/';

crlbFiles = {...
    'CRLB_data_N41.mat', ...
    'CRLB_data_N21.mat', ...
    'CRLB_data_N11.mat', ...
    'CRLB_data_N9.mat', ...
    'CRLB_data_N7.mat', ...
    'CRLB_data_N5.mat', ...
    };
savefileNames = {...
    'hist_all_variance_crlb_N41.csv', ...
    'hist_all_variance_crlb_N21.csv', ...
    'hist_all_variance_crlb_N11.csv', ...
    'hist_all_variance_crlb_N9.csv', ...
    'hist_all_variance_crlb_N7.csv', ...
    'hist_all_variance_crlb_N5.csv' ...
    };

%%
crlb_loaded = false;
saveFilename = 'hist_all_variance_fixed.csv';
mp;

%%
crlb_loaded = true;

for i = 1:length(crlbFiles)
    cd aoa_crlb_data;
    load(crlbFiles{i});
    saveFilename = savefileNames{i};
    cd ..;
    mp;
end

fig_dist_error;