clear;
timeStamp = datestr(now, 'yyyy-mm-dd, HHMMSS');
mkdir('mp_result/',timeStamp);
saveLocation = strcat('mp_result/',timeStamp,'/');

%%
crlbFiles = {...
    'CRLB_data_N41.mat', ...
    'CRLB_data_N21.mat', ...
    'CRLB_data_N11.mat', ...
    'CRLB_data_N9.mat', ...
    'CRLB_data_N7.mat', ...
    'CRLB_data_N5.mat', ...
    };
savefileNames = {...
    'hist_all_variance_crlb_N41.csv', ...
    'hist_all_variance_crlb_N21.csv', ...
    'hist_all_variance_crlb_N11.csv', ...
    'hist_all_variance_crlb_N9.csv', ...
    'hist_all_variance_crlb_N7.csv', ...
    'hist_all_variance_crlb_N5.csv' ...
    };

%%
b_vary_noise_by_AOA = false;
saveFilename = 'hist_all_variance_fixed.csv';
tic;
mp;
toc;
%%
b_vary_noise_by_AOA = true;
for i = 1:length(crlbFiles)
    cd aoa_crlb_data;
    load(crlbFiles{i});
    saveFilename = savefileNames{i};
    cd ..;
    mp;
end

fig_dist_error;